/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 House.glb 
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'

export const House = ({position, rotation, ...props}) => {
  const { nodes, materials } = useGLTF('/models/House.glb');
  position = useMemo(() => position, []);
  rotation = useMemo(() => rotation, []);
  // console.log(position)
  // console.log(rotation)

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.house.geometry} material={materials.None} position={position} rotation={rotation} scale={4} castShadow/>
    </group>
  )
}

useGLTF.preload('/House.glb')
