/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Pine Trees.glb 
*/

import React, { useRef, useMemo } from 'react'
import { useGLTF } from '@react-three/drei'

export function Pine(props) {
  const { nodes, materials } = useGLTF('/models/Pine Trees.glb')
  const position = useMemo(() => props.position, []);
  console.log(position)

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={620} position={position} castShadow>
        <mesh geometry={nodes.Resource_PineTree_Group_1.geometry} material={materials.Wood} />
        <mesh geometry={nodes.Resource_PineTree_Group_2.geometry} material={materials.Green} />
      </group>
    </group>
  )
}

useGLTF.preload('/Pine Trees.glb')
