/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Rock1.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Rock1 = ({position, ...props}) => {
  const { nodes, materials } = useGLTF('/models/Rock1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock.geometry} material={materials.Rock} position={position} rotation={[-Math.PI / 1, 0, 0]} scale={3} />
    </group>
  )
}

useGLTF.preload('/Rock1.glb')
