/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Rock2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export const Rock2 = ({position, props}) => {
  const { nodes, materials } = useGLTF('/models/Rock2.glb')
  // materials.Rock.color.setHex("#b2713d")
  materials.Rock.color.r = 255;
  materials.Rock.color.g = 3;
  materials.Rock.color.b = 255;
  console.log(materials.Rock, "ROCKS")
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Rock2.geometry} material={materials.Rock} position={position} rotation={[-Math.PI / 2,0, Math.PI/2]} scale={4} castShadow/>
      
    </group>
  )
}

useGLTF.preload('/Rock2.glb')
